FROM python:3

MAINTAINER jo-dev413

WORKDIR /app/discord_bot

RUN apt-get update

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade setuptools
RUN python3 -m pip install -U discord.py
RUN python3 -m pip install -U mysql-connector-python